server:
  port: 9082

spring:
  datasource:
    url: jdbc:mysql://rm-uf6651m82zm5ov296io.mysql.rds.aliyuncs.com/ces_show?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Uaes#1234
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true