########################################
###服务器配置
########################################
server:
  port: 9018


########################################
###数据库配置
########################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ces
    username: root
    password: 1991
    driver-class-name: com.mysql.jdbc.Driver


########################################
###Mybatis设置
########################################
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

