########################################
###server config
########################################
server:
  port: 9018


########################################
###database config
########################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ces_show?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1991
    driver-class-name: com.mysql.jdbc.Driver


########################################
###Mybatis config
########################################
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

