server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_yuanliang
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: provider-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
